### ISSUE TITLE
支持 el-table 的 table-layout="auto" 属性吗

### ISSUE THREAD

**Issue by GitHub-h1999** [ChongYu-Yease/vue3-el-table-sticky-plugin#1]
支持 el-table 的 table-layout="auto" 属性吗?

**Comment by xcy960815** [comment]
你好，感谢你的支持，当时这个指令开发时间紧迫，只支持了常规的el-table属性，没有考虑到你说的这个table-layout属性，不过你可以尝试下，个人感觉大概率没问题

**Comment by xcy960815** [comment]
你好，我看了一下，确实如你所说不支持的，我尽快修复，感谢指正

**Comment by xcy960815** [comment]
很抱歉的告诉你，element-plus 的table组件在我本地加上table-layout="auto"在组件渲染时会拿不到table-header节点，所以本插件也就会跟着报错了，我已向element官方提交issues，等待他们修复此问题，这个插件也会跟着好起来，我今晚又做了一些调整，在不存在able-layout="auto" 的时候 吸顶效果更精准，详情请见 readme.md
