### ISSUE TITLE
窗口resize的时候有问题

### ISSUE THREAD

**Issue by qingfengmy** [ChongYu-Yease/vue3-el-table-sticky-plugin#2]
怎么处理窗口resize的问题

**Comment by qingfengmy** [comment]
<img width="1432" alt="图片" src="https://user-images.githubusercontent.com/4978379/190563728-1073f4b5-4445-4f5c-b576-ab0e0d98b5fe.png">


top不为0时，滚动到顶部后，再resize窗口，吸顶的表头下不来了

**Comment by xcy960815** [comment]
ok，感谢指出错误，今晚我来看下，或者我看你也将项目启动起来了，所有的操作逻辑都是在table-sticky.ts里面，你有空的话给看下也行😄

**Comment by xcy960815** [comment]
问题已经定位到了，已经修复发布新版本0.0.9，感恩❤

**Comment by qingfengmy** [comment]
问题还是没有解决，可能是我没有描述清楚。我是滚到到吸顶后，再resize屏幕，此时header会一直吸顶，下不来。

我看了下代码，resize的时候，会重新执行
```
  private updateTableStickyConfig(option: Option): void {
    const uid = this.getUid(option)
    const currentTableStickyConfig = this.getCurrentTableStickyConfig(option)
    console.log('333', this.getTableHeaderCurrentTop(option))
    this.tableStickyConfigs.set(uid, {
      ...currentTableStickyConfig,
      tableWidth: option.tableElement.getBoundingClientRect().width,
      fixedTop: option.binding.value ? option.binding.value.top : this.getTableHeaderCurrentTop(option),
      tableHeaderOriginalTop: this.getTableHeaderCurrentTop(option)
    })

  }
```
此时的header因为在吸顶位置，所以距离顶部的高度此时是错的，会取到48.

所以这里应该有条件判断，如果初始有值，这个tableHeaderOriginalTop就不应该再取了。我觉得是这样的， 可能作者有更好的办法

**Comment by qingfengmy** [comment]
这样
···
  /**
   * @desc 更新TableStickyConfig配置
   * @param {Option} option 
   * @returns { void }
   */
  private updateTableStickyConfig(option: Option): void {
    const uid = this.getUid(option)
    const currentTableStickyConfig = this.getCurrentTableStickyConfig(option)
    const tableHeaderOriginalTop = currentTableStickyConfig.tableHeaderOriginalTop ? currentTableStickyConfig.tableHeaderOriginalTop : this.getTableHeaderCurrentTop(option);
    this.tableStickyConfigs.set(uid, {
      ...currentTableStickyConfig,
      tableWidth: option.tableElement.getBoundingClientRect().width,
      fixedTop: option.binding.value ? option.binding.value.top : this.getTableHeaderCurrentTop(option),
      tableHeaderOriginalTop
    })
  }
···

**Comment by xcy960815** [comment]
> 这样 ··· /**
> 
> * @desc更新TableStickyConfig配置
> * @param{选项} 选项
> * @returns{ void } 
>   */ 
>   private updateTableStickyConfig(option: Option): void { 
>   const uid = this.getUid(option) 
>   const currentTableStickyConfig = this.getCurrentTableStickyConfig(option) 
>   const tableHeaderOriginalTop = currentTableStickyConfig.tableHeaderOriginalTop ? currentTableStickyConfig.tableHeaderOriginalTop : this.getTableHeaderCurrentTop(option); 
>   this.tableStickyConfigs.set(uid, { 
>   ...currentTableStickyConfig, 
>   tableWidth: option.tableElement.getBoundingClientRect().width, 
>   fixedTop: option.binding.value ? option.binding.value.top : this.getTableHeaderCurrentTop(option), 
>   tableHeaderOriginalTop 
>   }) 
>   } 
>   ···

感谢指正不足之处，谢谢你~
